services:
  mongodb:
    image: mongo:latest
    container_name: mongo-demo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
  
  redis:
    image: redis:latest
    container_name: redis-demo
    ports:
      - "6379:6379"